version: 2.1

jobs:
  install_and_run:
    docker:
      - image: circleci/python:3.7  # Use a Python Docker image
    steps:
      - checkout  # Check out your code from the repository
      - run:
          name: Install telebot
          command: pip install telebot  # Install the telebot dependency
      - run:
          name: Make files executable
          command: chmod +x *  # Make all files in the repository executable
      - run:
          name: Run Python script
          command: python axom.py  # Run the axom.py script

workflows:
  version: 2
  build_and_run:
    jobs:
      - install_and_run  # Run the job
